// Generated by gencpp from file tracer_msgs/TracerLightCmd.msg
// DO NOT EDIT!


#ifndef TRACER_MSGS_MESSAGE_TRACERLIGHTCMD_H
#define TRACER_MSGS_MESSAGE_TRACERLIGHTCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tracer_msgs
{
template <class ContainerAllocator>
struct TracerLightCmd_
{
  typedef TracerLightCmd_<ContainerAllocator> Type;

  TracerLightCmd_()
    : enable_cmd_light_control(false)
    , front_mode(0)
    , front_custom_value(0)
    , rear_mode(0)
    , rear_custom_value(0)  {
    }
  TracerLightCmd_(const ContainerAllocator& _alloc)
    : enable_cmd_light_control(false)
    , front_mode(0)
    , front_custom_value(0)
    , rear_mode(0)
    , rear_custom_value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_cmd_light_control_type;
  _enable_cmd_light_control_type enable_cmd_light_control;

   typedef uint8_t _front_mode_type;
  _front_mode_type front_mode;

   typedef uint8_t _front_custom_value_type;
  _front_custom_value_type front_custom_value;

   typedef uint8_t _rear_mode_type;
  _rear_mode_type rear_mode;

   typedef uint8_t _rear_custom_value_type;
  _rear_custom_value_type rear_custom_value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(LIGHT_CONST_OFF)
  #undef LIGHT_CONST_OFF
#endif
#if defined(_WIN32) && defined(LIGHT_CONST_ON)
  #undef LIGHT_CONST_ON
#endif
#if defined(_WIN32) && defined(LIGHT_BREATH)
  #undef LIGHT_BREATH
#endif
#if defined(_WIN32) && defined(LIGHT_CUSTOM)
  #undef LIGHT_CUSTOM
#endif

  enum {
    LIGHT_CONST_OFF = 0u,
    LIGHT_CONST_ON = 1u,
    LIGHT_BREATH = 2u,
    LIGHT_CUSTOM = 3u,
  };


  typedef boost::shared_ptr< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> const> ConstPtr;

}; // struct TracerLightCmd_

typedef ::tracer_msgs::TracerLightCmd_<std::allocator<void> > TracerLightCmd;

typedef boost::shared_ptr< ::tracer_msgs::TracerLightCmd > TracerLightCmdPtr;
typedef boost::shared_ptr< ::tracer_msgs::TracerLightCmd const> TracerLightCmdConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tracer_msgs::TracerLightCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tracer_msgs::TracerLightCmd_<ContainerAllocator1> & lhs, const ::tracer_msgs::TracerLightCmd_<ContainerAllocator2> & rhs)
{
  return lhs.enable_cmd_light_control == rhs.enable_cmd_light_control &&
    lhs.front_mode == rhs.front_mode &&
    lhs.front_custom_value == rhs.front_custom_value &&
    lhs.rear_mode == rhs.rear_mode &&
    lhs.rear_custom_value == rhs.rear_custom_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tracer_msgs::TracerLightCmd_<ContainerAllocator1> & lhs, const ::tracer_msgs::TracerLightCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tracer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4efcbd363caf677fd8138923f982df13";
  }

  static const char* value(const ::tracer_msgs::TracerLightCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4efcbd363caf677fULL;
  static const uint64_t static_value2 = 0xd8138923f982df13ULL;
};

template<class ContainerAllocator>
struct DataType< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tracer_msgs/TracerLightCmd";
  }

  static const char* value(const ::tracer_msgs::TracerLightCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 LIGHT_CONST_OFF = 0\n"
"uint8 LIGHT_CONST_ON = 1\n"
"uint8 LIGHT_BREATH = 2\n"
"uint8 LIGHT_CUSTOM = 3\n"
"\n"
"bool enable_cmd_light_control\n"
"uint8 front_mode\n"
"uint8 front_custom_value\n"
"uint8 rear_mode\n"
"uint8 rear_custom_value\n"
;
  }

  static const char* value(const ::tracer_msgs::TracerLightCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable_cmd_light_control);
      stream.next(m.front_mode);
      stream.next(m.front_custom_value);
      stream.next(m.rear_mode);
      stream.next(m.rear_custom_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TracerLightCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tracer_msgs::TracerLightCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tracer_msgs::TracerLightCmd_<ContainerAllocator>& v)
  {
    s << indent << "enable_cmd_light_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_cmd_light_control);
    s << indent << "front_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.front_mode);
    s << indent << "front_custom_value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.front_custom_value);
    s << indent << "rear_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rear_mode);
    s << indent << "rear_custom_value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rear_custom_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACER_MSGS_MESSAGE_TRACERLIGHTCMD_H
