controller_list:
  - name: left_aubo_i5_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_arm_shoulder_joint
      - left_arm_upperArm_joint
      - left_arm_foreArm_joint
      - left_arm_wrist1_joint
      - left_arm_wrist2_joint
      - left_arm_wrist3_joint
  - name: right_aubo_i5_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_arm_shoulder_joint
      - right_arm_upperArm_joint
      - right_arm_foreArm_joint
      - right_arm_wrist1_joint
      - right_arm_wrist2_joint
      - right_arm_wrist3_joint
